## 라이브러리 및 데이터 목록 불러오기
2018년~2023년 사이 서울 내의 생활물류 데이터

In [39]:
import pandas as pd
import numpy as np

import os
import glob

path = 'C:\\Users\\PC\\Desktop\\demand_prediction'

In [40]:
os.listdir(path)

['.ipynb_checkpoints',
 '1. seoul_to_seoul.ipynb',
 '2. all_to_seoul.ipynb',
 'practice.ipynb',
 'seoulGuGu',
 'seoulGuGu.csv',
 'sidoSeoulgu']

In [41]:
data_list = os.listdir(path+'/seoulGuGu')

## 배송일자 + 수하인 구 기준으로 SUM 그룹핑

In [43]:
seoulGuGu = pd.DataFrame(columns=['배송년월일', '수하인_구명', '수하인_구코드', '대분류_착지물동량 가구/인테리어', '대분류_착지물동량 기타',
       '대분류_착지물동량 도서/음반', '대분류_착지물동량 디지털/가전', '대분류_착지물동량 생활/건강',
       '대분류_착지물동량 스포츠/레저', '대분류_착지물동량 식품', '대분류_착지물동량 출산/육아', '대분류_착지물동량 패션의류',
       '대분류_착지물동량 패션잡화', '대분류_착지물동량 화장품/미용'])

for data_dir in data_list:
    data = pd.read_csv(path + '/seoulGuGu/' + data_dir, encoding="euc-kr")
    data = data.groupby(['배송년월일', '수하인_구명', '수하인_구코드'])[['대분류_착지물동량 가구/인테리어', '대분류_착지물동량 기타',
           '대분류_착지물동량 도서/음반', '대분류_착지물동량 디지털/가전', '대분류_착지물동량 생활/건강',
           '대분류_착지물동량 스포츠/레저', '대분류_착지물동량 식품', '대분류_착지물동량 출산/육아', '대분류_착지물동량 패션의류',
           '대분류_착지물동량 패션잡화', '대분류_착지물동량 화장품/미용']].sum().reset_index()
    seoulGuGu = pd.concat([seoulGuGu, data])
    del data

seoulGuGu.reset_index(drop=True, inplace=True)
seoulGuGu = seoulGuGu.astype(int, errors='ignore')

In [44]:
seoulGuGu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54558 entries, 0 to 54557
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   배송년월일              54558 non-null  object
 1   수하인_구명             54558 non-null  object
 2   수하인_구코드            54558 non-null  object
 3   대분류_착지물동량 가구/인테리어  54558 non-null  int32
 4   대분류_착지물동량 기타       54558 non-null  int32
 5   대분류_착지물동량 도서/음반    54558 non-null  int32
 6   대분류_착지물동량 디지털/가전   54558 non-null  int32
 7   대분류_착지물동량 생활/건강    54558 non-null  int32
 8   대분류_착지물동량 스포츠/레저   54558 non-null  int32
 9   대분류_착지물동량 식품       54558 non-null  int32
 10  대분류_착지물동량 출산/육아    54558 non-null  int32
 11  대분류_착지물동량 패션의류     54558 non-null  int32
 12  대분류_착지물동량 패션잡화     54558 non-null  int32
 13  대분류_착지물동량 화장품/미용   54558 non-null  int32
dtypes: int32(11), object(3)
memory usage: 3.5+ MB

In [45]:
seoulGuGu.describe()

,대분류_착지물동량 가구/인테리어,대분류_착지물동량 기타,대분류_착지물동량 도서/음반,대분류_착지물동량 디지털/가전,대분류_착지물동량 생활/건강,대분류_착지물동량 스포츠/레저,대분류_착지물동량 식품,대분류_착지물동량 출산/육아,대분류_착지물동량 패션의류,대분류_착지물동량 패션잡화,대분류_착지물동량 화장품/미용
count,54558.000000,54558.000000,54558.000000,54558.000000,54558.000000,54558.000000,54558.000000,54558.000000,54558.000000,54558.000000,54558.000000
mean,184.342443,1235.914495,344.845870,838.696635,1053.248470,149.594927,958.508376,148.004197,1912.087778,739.658584,603.943895
std,173.819184,1036.264550,327.491486,754.469925,963.015258,141.042905,916.406803,132.319666,1520.158059,601.841886,544.349411
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,14.000000,262.000000,89.000000,76.000000,128.000000,14.000000,120.000000,19.000000,372.000000,122.000000,69.000000
50%,169.000000,1192.000000,312.000000,795.000000,976.000000,134.000000,836.000000,137.000000,1902.000000,733.000000,564.000000
75%,273.000000,1772.000000,482.000000,1238.000000,1524.000000,219.000000,1373.000000,223.000000,2833.000000,1086.000000,865.000000
max,2038.000000,10372.000000,10882.000000,6503.000000,15011.000000,1313.000000,11799.000000,1560.000000,11076.000000,4655.000000,4699.000000

## csv로 저장

In [46]:
seoulGuGu.to_csv("seoulGuGu.csv", index=False, encoding="euc-kr")

In [38]:
seoulGuGu

,배송년월일,수하인_구명,수하인_구코드,대분류_착지물동량 가구/인테리어,대분류_착지물동량 기타,대분류_착지물동량 도서/음반,대분류_착지물동량 디지털/가전,대분류_착지물동량 생활/건강,대분류_착지물동량 스포츠/레저,대분류_착지물동량 식품,대분류_착지물동량 출산/육아,대분류_착지물동량 패션의류,대분류_착지물동량 패션잡화,대분류_착지물동량 화장품/미용
0,20180101,강남구,11680,57,26,28,6,123,14,21,0,80,93,6
1,20180101,강동구,11740,32,17,11,0,60,9,15,3,33,35,0
2,20180101,강북구,11305,22,9,7,0,53,4,0,0,24,17,5
3,20180101,강서구,11500,40,26,45,3,104,16,34,0,71,103,7
4,20180101,관악구,11620,32,20,16,3,120,15,30,0,43,58,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
770,20231231,용산구,11170,4,27,0,17,50,10,12,0,35,44,3
771,20231231,은평구,11380,16,8,0,31,67,14,10,5,67,99,6
772,20231231,종로구,11110,0,8,5,10,30,8,9,0,19,29,48
773,20231231,중구,11140,4,37,0,3,32,4,5,3,23,66,63
774,20231231,중랑구,11260,13,10,0,23,64,5,0,7,68,72,4